# Generated by Django 3.0.5 on 2020-04-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawnmower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('photo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='which product', max_length=100)),
                ('description', models.CharField(default='product description', max_length=100)),
                ('preview_url', models.TextField()),
                ('lawnmower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizers', to='grass_cutting.Lawnmower')),
            ],
        ),
    ]
